services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  database-service:
    build: ./database-service
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  inference-service:
    build: ./inference-service
    ports:
      - "8002:8000"
    depends_on:
      - database-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - INFERENCE_URL=http://inference-service:8000/predict
      - DB_LOG_URL=http://database-service:8000/logs
      - DB_HISTORY_URL=http://database-service:8000/history
    depends_on:
      - inference-service

  dashboard-ui:
    build: ./dashboard-ui
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_BASE_URL=http://api-gateway:8080
    depends_on:
      - api-gateway

volumes:
  mongo_data: