apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: maintenance.local
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      - path: /openapi.json
        pathType: Exact
        backend:
          service:
            name: api-gateway
            port:
              number: 8080