apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard-deployment.yaml
  - database-deployment.yaml
  - gateway-deployment.yaml
  - hpa.yaml
  - inference-deployment.yaml
  - ingress-nginx-lb.yaml
  - ingress-dashboard.yaml
  - ingress-api.yaml
  - ingress-docs.yaml